[tool.poetry]
name = "realbook"
version = "0.1.0"
description = "A simple program to create lead sheets as those found on the realbook"
authors = ["Erick G. Islas-Osuna <erickisos653@gmail.com>"]
packages = [
    { include = "realbook", from = "src" }
]

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
PySide6 = "^6.4.1"

[tool.poetry.dev-dependencies]
tox = "^4.0.14"
mypy = "^0.991"
black = "^22.12.0"
isort = "^5.10.1"
bandit = "^1.7.4"
flake8 = "^6.0.0"
pytest = "^7.2.0"
pre-commit = "^2.20.0"
hypothesis = {extras = ["zoneinfo"], version = "^6.61.0"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length=79
skip-string-normalization = true
target-version=['py39']
preview = true
exclude = '''
/(
    /.git
  | /.mypy_cache
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"

[tool.mypy]
ignore_missing_imports = true
